version: 2.1
jobs:
  run_tests:
    docker:
      - image: cypress/base:12
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Compile and start development server on port 3000
          command: npm start
          background: true
      - run:
          name: Run e2e tests with Cypruss via cypress run
          command: $(npm bin)/cypress run --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results

workflows:
  build_and_test:
    jobs:
      - run_tests
