--- 
defaults: 
  docker: 
    - 
      environment: 
        TERM: xterm
      image: "cypress/base:8"
  working_directory: ~/app
jobs: 
  build: 
    docker: 
      - 
        environment: 
          TERM: xterm
        image: "cypress/base:8"
    steps: 
      - checkout
      - 
        run: pwd
      - 
        run: ls
      - 
        restore_cache: 
          keys: 
            - "v2-deps-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
            - "v2-deps-{{ .Branch }}-"
            - v2-deps-
      - 
        run: "npm install"
      - 
        save_cache: 
          key: "v2-deps-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
          paths: 
            - ~/.npm
            - ~/.cache
      - 
        persist_to_workspace: 
          paths: 
            - .cache
            - app
          root: ~/
    working_directory: ~/app
  start: 
    executor: node/default
    steps: 
      - checkout
      - node/install-packages
      - 
        run: 
          comamnd: "npm run start"
  testA: 
    docker: 
      - 
        environment: 
          TERM: xterm
        image: "cypress/base:8"
    steps: 
      - 
        attach_workspace: 
          at: ~/
      - 
        run: "ls -la cypress"
      - 
        run: "ls -la cypress/integration"
      - 
        run: 
          command: "$(npm bin)/cypress run --spec cypress/integration/Login/login_spec.js"
          name: "Running E2E tests A"
      - 
        store_test_results: 
          path: results
      - 
        store_artifacts: 
          path: cypress/videos
      - 
        store_artifacts: 
          path: cypress/screenshots
    working_directory: ~/app
orbs: 
  node: circleci/node@5.0.2
version: 2
workflows: 
  build_and_test: 
    jobs: 
      - build
      - start
      - 
        testA: 
          requires: 
            - build
  version: 2
